[package]
name = "span"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.166", features = ["derive"] }

[dev-dependencies]
#pretty_assertions = "1.4.0"
#rstest = "0.21.0"
